### ISSUE TITLE
Two IDs returned in geo-endpoint

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/geo-endpoint#1]
Hi,

I requested `geo/district` endpoint and found that there are two IDs (`id` and `OBJECTID`) for each district. And also I have to use `object_id` param to get a single district while I can get single objects with `id` param in party-endpoint and candidate-endpoint.

Thanks.

**Comment by tyohan** [comment]
@DragonVirus i think we need more documentation on this like what's the difference between id and object_id. I know it's not consistent to have different way to access the data but I think we can't change it for now because we have an SDK developed already. cc @phyominthu

**Comment by DragonVirus** [comment]
ok @tyohan ... but we can add a query to get the single object with id if needed. Will it make the developers more confused ? cc @ThetPaing

**Comment by tyohan** [comment]
Yes, i Think it's better to make them able to get single object also using
id. But make sure we put it also on documentation.
