### ISSUE TITLE
"no_geo=true" param doesn't work in Getting district by ID or by latitude/longitude

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/geo-endpoint#3]
Hi,

I requested `geo/district/<id>` with param `no_geo=true` but there's always `geometry` returned with district regardless of this param.

`geo/district/find` also disregarding this param.

Thanks.

**Comment by ThetPaing** [comment]
There is no `no_geo=true` option in single `geometry` Get Request.  Because i think only one single data will need `geometry` field.

**Comment by phyominthu** [comment]
Sorry I'm not clear about it. But lets say I don't do 'geometry coordinates' thing in the app. It'd be unnecessary for me to request big load of coordinates data, a request without this data will be more efficient (or fast?), I guess.

**Comment by ThetPaing** [comment]
`no_geo=true` option only support in `/geo/district` [" get all geo location in doc" ] . Not support in other request. But if u want like this. i will add `no_geo=true` option in other.

**Comment by phyominthu** [comment]
Please do. I'll be grateful about it. Thanks. :)
