### ISSUE TITLE
"no_geo=false" doesn't work in getting district by ID and by latitude/longitude

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/geo-endpoint#6]
Hi,

Issue https://github.com/MyanmarAPI/geo-endpoint/issues/3 has been fixed and I can now filter out `geometry` with param `no_geo=true`. But I found `no_geo=false` not returning geometry data.

When I request with `no_geo=true`, API doesn't return `geometry`. This is correct.
When I request with `no_geo=false`. API should return `geometry`. It doesn't return that data now.

This is happening on both `district/<id>` and `district/find`.

**Comment by phyominthu** [comment]
Just tried this out. API is not yet updated with this fix? @ThetPaing

**Comment by ThetPaing** [comment]
@phyominthu i trying to update in server.
