### ISSUE TITLE
Question marks in geo json

### ISSUE THREAD

**Issue by Wyclef** [MyanmarAPI/geo-endpoint#8]
I think `DT_Mya` is supposed be Myanmar text?

![capture](https://cloud.githubusercontent.com/assets/2858410/9867136/4310df68-5b90-11e5-9074-8442cc191e07.PNG)

**Comment by DragonVirus** [comment]
This field is still ???? but @mapmeld already added properties for myanmar text so, i'm gonna close this issue.
