### ISSUE TITLE
Duplicate data values in geo/lowerhouse endpoint

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/geo-endpoint#9]
Hi,

There are different keys for same values in the response, e.g. state, state pcode, township, township pcode.

![screen shot 2015-09-15 at 6 34 08 pm](https://cloud.githubusercontent.com/assets/6995089/9875987/9009cce2-5bd8-11e5-96bc-6ff265b2d321.png)

**Comment by tyohan** [comment]
@ThetPaing could check this, and close it if it's fixed with new dataset
